import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import FlyonuiScript from "@/components/FlyonuiScript";
import "./globals.scss";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Edusia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={workSans.variable}>
        {children}
      </body>
      <FlyonuiScript />
    </html>
  );
}
